AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM role for GitHub Actions OIDC access'

Parameters:
  GitHubOrganization:
    Type: String
    Description: GitHub organization or username
    Default: harvardpan
  
  GitHubRepository:
    Type: String
    Description: GitHub repository name
    Default: banditsNotification

Resources:
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActions-BanditsNotification
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': sts.amazonaws.com
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubOrganization}/${GitHubRepository}:*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
      Policies:
        - PolicyName: LambdaDeploymentPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - lambda:*
                  - iam:GetRole
                  - iam:PassRole
                  - iam:CreateRole
                  - iam:AttachRolePolicy
                  - iam:PutRolePolicy
                  - iam:DetachRolePolicy
                  - iam:DeleteRole
                  - iam:DeleteRolePolicy
                  - iam:UpdateAssumeRolePolicy
                  - iam:TagRole
                  - iam:UntagRole
                  - iam:ListInstanceProfilesForRole
                  - events:*
                  - logs:*
                  - sqs:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - 'arn:aws:s3:::bandits-notification-*'
                  - 'arn:aws:s3:::bandits-notification-*/*'
                  - 'arn:aws:s3:::banditsnotifier-storage'
                  - 'arn:aws:s3:::banditsnotifier-storage/*'
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:DescribeKey
                Resource: 'arn:aws:kms:us-east-1:028036396420:alias/BanditsNotifierKMSKey'

Outputs:
  RoleArn:
    Description: ARN of the GitHub Actions role
    Value: !GetAtt GitHubActionsRole.Arn
    Export:
      Name: GitHubActionsRoleArn